# Generated by Django 5.2.6 on 2025-09-21 10:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('correo', models.CharField(db_column='correo', max_length=50)),
                ('nombre_usuario', models.CharField(db_column='nombre_usuario', max_length=10)),
                ('contrasena', models.TextField(db_column='contrasena')),
            ],
            options={
                'db_table': '"USUARIO"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='administrador', serialize=False, to='users.usuario')),
                ('acceso', models.BooleanField(db_column='acceso', default=True)),
            ],
            options={
                'db_table': '"ADMINISTRADOR"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='cliente', serialize=False, to='users.usuario')),
                ('saldo', models.DecimalField(db_column='saldo', decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('excliente', models.BooleanField(db_column='excliente', default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
            ],
            options={
                'db_table': '"CLIENTE"',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['correo'], name='ix_usuario_correo'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['nombre_usuario'], name='ix_usuario_nombre'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('nombre_usuario', 'correo'), name='UQ_CONSTRAIN'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['saldo'], name='ix_cliente_saldo'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('saldo__gte', 0)), name='CHECK_SALDO'),
        ),
    ]
