/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.1 		*/
/*  Created On : 22-sep.-2025 10:05:41 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS usuario_id_usuario_seq
;

DROP SEQUENCE IF EXISTS autor_id_autor_seq
;

DROP SEQUENCE IF EXISTS categoria_id_categoria_seq
;

DROP SEQUENCE IF EXISTS producto_id_producto_seq
;

DROP SEQUENCE IF EXISTS imagen_producto_id_imagen_producto_seq
;

DROP SEQUENCE IF EXISTS comentario_producto_id_comentario_producto_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "USUARIO" CASCADE
;

DROP TABLE IF EXISTS "ADMINISTRADOR" CASCADE
;

DROP TABLE IF EXISTS "CLIENTE" CASCADE
;

DROP TABLE IF EXISTS "AUTOR" CASCADE
;

DROP TABLE IF EXISTS "CATEGORIA" CASCADE
;

DROP TABLE IF EXISTS "PRODUCTO" CASCADE
;

DROP TABLE IF EXISTS "IMAGEN_PRODUCTO" CASCADE
;

DROP TABLE IF EXISTS "DETALLES_PRODUCTO" CASCADE
;

DROP TABLE IF EXISTS "CALIFICACION_PRODUCTO" CASCADE
;

DROP TABLE IF EXISTS "COMENTARIO_PRODUCTO" CASCADE
;

DROP TABLE IF EXISTS "COMPRA_PRODUCTO" CASCADE
;

/* Create Tables */

CREATE TABLE "USUARIO"
(
	id_usuario bigint NOT NULL   DEFAULT NEXTVAL(('"usuario_id_usuario_seq"'::text)::regclass),
	correo varchar(50) NOT NULL,
	nombre_usuario varchar(10) NOT NULL,
	contrasena varchar(128) NOT NULL,
	CONSTRAINT "PK_USUARIO" PRIMARY KEY (id_usuario),
	CONSTRAINT "UQ_CONSTRAIN" UNIQUE (nombre_usuario,correo)
)
;

CREATE TABLE "ADMINISTRADOR"
(
	id_usuario bigint NOT NULL,
	acceso boolean NOT NULL   DEFAULT true,
	CONSTRAINT "PK_ADMINISTRADOR" PRIMARY KEY (id_usuario),
	CONSTRAINT "FK_ID_USUARIO" FOREIGN KEY (id_usuario) REFERENCES "USUARIO" (id_usuario) ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE "CLIENTE"
(
	id_usuario bigint NOT NULL,
	excliente boolean NOT NULL   DEFAULT false,
	fecha_creacion timestamp without time zone NOT NULL   DEFAULT now(),
	saldo numeric(12,2) NULL   DEFAULT 0,
	CONSTRAINT "PK_CLIENTE" PRIMARY KEY (id_usuario),
	CONSTRAINT "CHECK_SALDO" CHECK (saldo>=0),
	CONSTRAINT "FK_ID_USUARIO" FOREIGN KEY (id_usuario) REFERENCES "USUARIO" (id_usuario) ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE "AUTOR"
(
	id_autor bigint NOT NULL   DEFAULT NEXTVAL(('"autor_id_autor_seq"'::text)::regclass),
	nombre varchar(50) NOT NULL,
	CONSTRAINT "PK_AUTOR" PRIMARY KEY (id_autor)
)
;

CREATE TABLE "CATEGORIA"
(
	id_categoria bigint NOT NULL   DEFAULT NEXTVAL(('"categoria_id_categoria_seq"'::text)::regclass),
	fecha timestamp without time zone NOT NULL   DEFAULT now(),
	nombre varchar(50) NOT NULL,
	descripcion text NULL,
	CONSTRAINT "PK_CATEGORIA" PRIMARY KEY (id_categoria)
)
;

CREATE TABLE "PRODUCTO"
(
	id_producto bigint NOT NULL   DEFAULT NEXTVAL(('"producto_id_producto_seq"'::text)::regclass),
	nombre varchar(50) NOT NULL,
	fecha timestamp without time zone NOT NULL   DEFAULT now(),
	archivo bytea NOT NULL,
	activo boolean NOT NULL   DEFAULT true,
	id_categoria bigint NULL,
	id_autor bigint NULL,
	CONSTRAINT "PK_PRODUCTO" PRIMARY KEY (id_producto),
	CONSTRAINT "FK_ID_AUTOR" FOREIGN KEY (id_autor) REFERENCES "AUTOR" (id_autor) ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT "FK_ID_CATEGORIA" FOREIGN KEY (id_categoria) REFERENCES "CATEGORIA" (id_categoria) ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE "IMAGEN_PRODUCTO"
(
	id_imagen_producto bigint NOT NULL   DEFAULT NEXTVAL(('"imagen_producto_id_imagen_producto_seq"'::text)::regclass),
	orden integer NOT NULL,
	archivo bytea NOT NULL,
	id_producto bigint NOT NULL,
	CONSTRAINT "PK_IMAGEN_PRODUCTO" PRIMARY KEY (id_imagen_producto),
	CONSTRAINT "FK_ID_PRODUCTO" FOREIGN KEY (id_producto) REFERENCES "PRODUCTO" (id_producto) ON DELETE Cascade ON UPDATE No Action
)
;

CREATE TABLE "DETALLES_PRODUCTO"
(
	id_producto bigint NOT NULL,
	precio numeric(12,2) NOT NULL,
	version varchar(50) NULL,
	descripcion text NULL,
	CONSTRAINT "PK_DETALLES_PRODUCTO" PRIMARY KEY (id_producto),
	CONSTRAINT "CHECK_PRECIO" CHECK (precio>=0),
	CONSTRAINT "FK_ID_PRODUCTO" FOREIGN KEY (id_producto) REFERENCES "PRODUCTO" (id_producto) ON DELETE Cascade ON UPDATE No Action
)
;

CREATE TABLE "CALIFICACION_PRODUCTO"
(
	id_usuario bigint NOT NULL,
	id_producto bigint NOT NULL,
	calificacion integer NOT NULL,
	fecha timestamp without time zone NOT NULL   DEFAULT now(),
	CONSTRAINT "PK_CALIFICACION_PRODUCTO" PRIMARY KEY (id_producto,id_usuario),
	CONSTRAINT "CHECK_CALIFICACION" CHECK (calificacion BETWEEN 1 AND 5),
	CONSTRAINT "FK_ID_CLIENTE" FOREIGN KEY (id_usuario) REFERENCES "CLIENTE" (id_usuario) ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT "FK_ID_PRODUCTO" FOREIGN KEY (id_producto) REFERENCES "PRODUCTO" (id_producto) ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE "COMENTARIO_PRODUCTO"
(
	id_comentario_producto bigint NOT NULL   DEFAULT NEXTVAL(('"comentario_producto_id_comentario_producto_seq"'::text)::regclass),
	descripcion text NOT NULL,
	fecha timestamp without time zone NOT NULL   DEFAULT now(),
	id_producto bigint NOT NULL,
	id_usuario bigint NOT NULL,
	CONSTRAINT "PK_COMENTARIO_PRODUCTO" PRIMARY KEY (id_comentario_producto),
	CONSTRAINT "FK_ID_CLIENTE" FOREIGN KEY (id_usuario) REFERENCES "CLIENTE" (id_usuario) ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT "FK_ID_PRODUCTO" FOREIGN KEY (id_producto) REFERENCES "PRODUCTO" (id_producto) ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE "COMPRA_PRODUCTO"
(
	id_producto bigint NOT NULL,
	id_usuario bigint NOT NULL,
	fecha timestamp without time zone NOT NULL   DEFAULT now(),
	CONSTRAINT "PK_COMPRA_PRODUCTO" PRIMARY KEY (id_producto,id_usuario),
	CONSTRAINT "FK_ID_CLIENTE" FOREIGN KEY (id_usuario) REFERENCES "CLIENTE" (id_usuario) ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT "FK_ID_PRODUCTO" FOREIGN KEY (id_producto) REFERENCES "PRODUCTO" (id_producto) ON DELETE No Action ON UPDATE No Action
)
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE usuario_id_usuario_seq INCREMENT 1 START 1
;

CREATE SEQUENCE autor_id_autor_seq INCREMENT 1 START 1
;

CREATE SEQUENCE categoria_id_categoria_seq INCREMENT 1 START 1
;

CREATE SEQUENCE producto_id_producto_seq INCREMENT 1 START 1
;

CREATE SEQUENCE imagen_producto_id_imagen_producto_seq INCREMENT 1 START 1
;

CREATE SEQUENCE comentario_producto_id_comentario_producto_seq INCREMENT 1 START 1
;
