# Generated by Django 5.2.6 on 2025-09-29 04:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.BigAutoField(db_column='id_autor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
            ],
            options={
                'db_table': '"AUTOR"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigAutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, db_column='fecha')),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
            ],
            options={
                'db_table': '"CATEGORIA"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('fecha', models.DateTimeField(blank=True, db_column='fecha')),
                ('archivo', models.BinaryField(db_column='archivo')),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('autor', models.ForeignKey(blank=True, db_column='id_autor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.autor')),
                ('categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.categoria')),
            ],
            options={
                'db_table': '"PRODUCTO"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallesProducto',
            fields=[
                ('producto', models.OneToOneField(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detalles', serialize=False, to='products.producto')),
                ('precio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('version', models.CharField(blank=True, db_column='version', max_length=50, null=True)),
            ],
            options={
                'db_table': '"DETALLES_PRODUCTO"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id_imagen_producto', models.BigAutoField(db_column='id_imagen_producto', primary_key=True, serialize=False)),
                ('orden', models.IntegerField(db_column='orden')),
                ('archivo', models.BinaryField(db_column='archivo')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='products.producto')),
            ],
            options={
                'db_table': '"IMAGEN_PRODUCTO"',
                'ordering': ['orden'],
                'managed': True,
            },
        ),
    ]
