# Generated by Django 5.2.6 on 2025-09-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='detallesproducto',
            name='descripcion',
            field=models.TextField(blank=True, db_column='descripcion', null=True),
        ),
    ]
