# Generated by Django 5.2.6 on 2025-09-29 05:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_producto_descripcion_and_more'),
        ('users', '0003_alter_cliente_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionProducto',
            fields=[
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='calificaciones', serialize=False, to='products.producto')),
                ('calificacion', models.IntegerField(db_column='calificacion', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='fecha')),
            ],
            options={
                'db_table': '"CALIFICACION_PRODUCTO"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ComentarioProducto',
            fields=[
                ('id_comentario_producto', models.BigAutoField(db_column='id_comentario_producto', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(db_column='descripcion')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='fecha')),
            ],
            options={
                'db_table': '"COMENTARIO_PRODUCTO"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompraProducto',
            fields=[
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='compras', serialize=False, to='products.producto')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='fecha')),
            ],
            options={
                'db_table': '"COMPRA_PRODUCTO"',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha'),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='precio',
            field=models.DecimalField(db_column='precio', decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='autor',
            field=models.ForeignKey(blank=True, db_column='id_autor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='products.autor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='products.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['nombre'], name='ix_categoria_nombre'),
        ),
        migrations.AddIndex(
            model_name='detallesproducto',
            index=models.Index(fields=['precio'], name='ix_det_precio'),
        ),
        migrations.AddIndex(
            model_name='imagenproducto',
            index=models.Index(fields=['producto', 'orden'], name='ix_img_prod_orden'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='ix_producto_nombre'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='ix_producto_activo'),
        ),
        migrations.AddConstraint(
            model_name='autor',
            constraint=models.UniqueConstraint(fields=('nombre',), name='UQ_AUTOR_NOMBRE'),
        ),
        migrations.AddConstraint(
            model_name='detallesproducto',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='CHECK_PRECIO'),
        ),
        migrations.AddField(
            model_name='calificacionproducto',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='users.cliente'),
        ),
        migrations.AddField(
            model_name='comentarioproducto',
            name='producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='products.producto'),
        ),
        migrations.AddField(
            model_name='comentarioproducto',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='users.cliente'),
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='users.cliente'),
        ),
        migrations.AddIndex(
            model_name='calificacionproducto',
            index=models.Index(fields=['usuario'], name='ix_calif_usuario'),
        ),
        migrations.AddConstraint(
            model_name='calificacionproducto',
            constraint=models.CheckConstraint(condition=models.Q(('calificacion__gte', 1), ('calificacion__lte', 5)), name='CHECK_CALIFICACION'),
        ),
        migrations.AddConstraint(
            model_name='calificacionproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'usuario'), name='PK_CALIFICACION_PRODUCTO'),
        ),
        migrations.AddIndex(
            model_name='comentarioproducto',
            index=models.Index(fields=['producto'], name='ix_comentario_producto'),
        ),
        migrations.AddIndex(
            model_name='comentarioproducto',
            index=models.Index(fields=['usuario'], name='ix_comentario_usuario'),
        ),
        migrations.AddIndex(
            model_name='comentarioproducto',
            index=models.Index(fields=['fecha'], name='ix_comentario_fecha'),
        ),
        migrations.AddIndex(
            model_name='compraproducto',
            index=models.Index(fields=['usuario'], name='ix_compra_usuario'),
        ),
        migrations.AddIndex(
            model_name='compraproducto',
            index=models.Index(fields=['fecha'], name='ix_compra_fecha'),
        ),
        migrations.AddConstraint(
            model_name='compraproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'usuario'), name='PK_COMPRA_PRODUCTO'),
        ),
    ]
